[project]
name = "snake-egg"

[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"

[project.optional-dependencies]
dev = [
  "mypy"
]
[tool.mypy]
ignore_missing_imports = false
warn_redundant_casts = true
check_untyped_defs = true
strict_equality = true
warn_unused_configs = true